"use client"
import { Header } from "@/stories/components/Header/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  const navItems = [
    {
      label: "Home",
      onClick: () => {
        console.log("My home");
      },
    },
    {
      label: "About",
      onClick: () => {
        console.log("About");
      },
    },
    {
      label: "Experience",
    },
    {
      label: "Work",
      onClick: () => {
        console.log("My Work");
      },
    },
  ];

export const HeaderApp = () => {
    return <Header></Header>
}