"use client"
import { Header } from "@/stories/organisms/Header/Header";
import styles from "./headerApp.module.scss";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  const navItems = [
    {
      label: "Home",
      onClick: () => {
        console.log("My home");
      },
      active: true,
    },
    {
      label: "About",
      onClick: () => {
        console.log("About");
      },
    },
    {
      label: "Experience",
    },
    {
      label: "Work",
      onClick: () => {
        console.log("My Work");
      },
    },
  ];

export const HeaderApp = () => {
    return <Header navItems={navItems} className={styles.headerApp}></Header>
}